### ISSUE TITLE
GoTo iz_max

### ISSUE THREAD

**Issue by jordanmb** [imeka/nnls#1]
I am actually triggering the panics, not sure how to fix it. I appreciate you porting this library, which otherwise works great.

**Comment by nilgoyette** [comment]
Hi @jordanmb, thank you for using/testing my library.

This being said, I can't debug anything if you only tell me that you trigger the panics. Can you provide more information? The best would be to have the `a` matrix and the `b` array (`nnls(a, b)`), but I understand if you're are unable to unwilling to share them.

**Comment by jordanmb** [comment]
I was able to find a smaller test example, but maybe it has to do with the precision? It's from real-world data so I don't have control over the b array values - which predominately aren't so close to zero.   

```
#[macro_use]
extern crate ndarray;
extern crate nnls;

#[test]
fn test_goto_error() {
    let a = array![
        [9.611001430700469e-8, 7.95765549922246e-17, 2.723479092534648e-44, 3.4490959105134237e-44],
        [7.95765549922246e-17, 2.0449818334851672e-7, 7.436056781569359e-44, 9.41733456542284e-44],
        [2.723479092534648e-44, 7.436056781569359e-44, 3.165150727363901e-7, 2.9014815452268743e-44],
        [3.4490959105134237e-44, 9.417334565422843e-44, 2.9014815452268743e-44, 4.344362859307413e-7]
    ];

    let b = array![
        -2.467866941671465e-17,
        -6.711852200648482e-17,
        3.630678603596055e-46,
        4.592379314173078e-46
    ];

    nnls::nnls(a.view(), b.view());
}

```

**Comment by jordanmb** [comment]
I think for now I can just take the norm of the b array and ensure that it's above some tolerance threshold. If this isn't something you want to fix, then it's at least worth a note in the docs.

**Comment by nilgoyette** [comment]
Thank you @jordanmb, this small example is more than I hoped for. The numbers are indeed really close to 0.0, but wathever the cause of the problem, I want this lib to have the same behaviour as the official `nnls` so I'll try to fix it.

I'll compare my version with the official version and get back to you when I have some free time at work.
